import abi from "./Transactions.json";

//for compiling--> gas fees was paid
//address to which Transactions are deployed to(generated by hardhat for the linked account)
export const contractAddress = "0xd6EBd35efbA2516a6a3DeaF63361f0a34e759032";
//accessed from ../smart_contract/artifacts/contracts/Transactions.sol/Transactions.json
//interaction with ethereum smart contract done with abi
export const contractABI = abi.abi;
